apiVersion: v1
kind: Service
metadata:
  name: flask-app-service-ip
  namespace: flask
  labels:
    app: flask-app
    version: v1
  annotations: {}
spec:
  selector:
    app: flask-app
    version: v1
  ports:
    - name: cce-service-0
      targetPort: 50100
      nodePort: 0
      port: 50100
      protocol: TCP
  type: ClusterIP
